---
title: "lab4"
author: "kwon"
date: "2018년 8월 8일"
output: html_document
---

```{r}
library(ISLR)
names(Smarket)
dim(Smarket)
summary(Smarket)
```
```{r}
pairs(Smarket)
cor(Smarket[,-9])
```

```{r}
attach(Smarket)
plot(Smarket$Volume)
```

## Logistic Regression
```{r}
glm.fits = glm(Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume, data= Smarket, family=binomial)
summary(glm.fits)
```
```{r}
contrasts(Direction)
```
```{r}
glm.probs = predict(glm.fits, type ="response")
glm.pred = rep("Down", 1250)
glm.pred[glm.probs>.5] = "Up"
table(glm.pred, Direction)
```

## Linear Discreminant Analysis
```{r}
require(MASS)
train = (Year<2005)
lda.fit = lda(Direction~Lag1+Lag2, data= Smarket, subset=train)
lda.fit
```
```{r}
plot(lda.fit)
```
```{r}
Smarket.2005 = Smarket[!train,]
Direction.2005 = Direction[!train]
lda.pred = predict(lda.fit, Smarket.2005)
names(lda.pred)
```
```{r}
lda.class = lda.pred$class
table(lda.class, Direction.2005)
mean(lda.class==Direction.2005)
```

## Quadratic Discriminant Analysis
```{r}
qda.fit = qda(Direction~Lag1+Lag2, data=Smarket, subset=train)
qda.fit
```
```{r}
qda.class=predict(qda.fit, Smarket.2005)$class
table(qda.class, Direction.2005)
mean(qda.class==Direction.2005)
```

## K-Nearest Neighbors
```{r}
require(class)
train.X = cbind(Lag1, Lag2)[train,]
test.X = cbind(Lag1, Lag2)[!train,]
train.Direction = Direction[train]
```
```{r}
set.seed(1)
knn.pred = knn(train.X, test.X, train.Direction, k=1)
table(knn.pred, Direction.2005)
```

```{r}
knn.pred = knn(train.X, test.X, train.Direction, k=3)
table(knn.pred, Direction.2005)
```







