---
title: "chp9 concept"
author: "kwon"
date: "2018년 8월 27일"
output: html_document
---

#1
##a
```{r}
x1 = seq(-1, 1, 0.1)
x2 = 1+3*x1

plot(x1,x2, type="l", col="red")
text(c(0), c(2), "smaller than 0", col="red")
text(c(0), c(-1), "greater than 0", col="red")
```

##b
```{r}
x1 = seq(-1, 1, 0.1)
x2 = 1+3*x1
plot(x1,x2, type="l", col="red")
text(c(0), c(2), "smaller than 0", col="red")
text(c(0), c(-1), "greater than 0", col="red")

x2 = 1-x1/2
lines(x1, x2, type="l", col="blue")
text(c(0), c(3), "greater than 0", col="blue")
text(c(0), c(-2), "smaller than 0", col="blue")

```

#2
##a
```{r}
plot(NA, NA, type="n", xlim=c(-4,2), ylim=c(-1,5), asp=1, xlab="X1", ylab="X2")
symbols(-1,2, circles=c(2), add=TRUE, inches=FALSE)

```
##b
```{r}
plot(NA, NA, type="n", xlim=c(-4,2), ylim=c(-1,5), asp=1, xlab="X1", ylab="X2")
symbols(-1,2, circles=c(2), add=TRUE, inches=FALSE)
text(-1, 2, "greater than 4")
text(-5, 2, "smaller than 4")
```

##c
```{r}
plot(NA, NA, type="n", xlim=c(-8,3), ylim=c(-2,10), asp=1, xlab="X1", ylab="X2")
symbols(-1,2, circles=c(2), add=TRUE, inches=FALSE)
x1 = c(-1, 2, 3)
x2 = c(1, 2, 8)
y= (x1+1)^2+(2-x2)^2 >4
points(x1, x2, col = as.factor(y), cex=2, pch=20)
```

##d
$$ (1+X_1)^2 + (2-X_2)^2 > 4 \\ 1 + 2 X_1 + X_1^2 + 4 - 4 X_2 + X_2^2 > 4 \\ 5 + 2 X_1 - 4 X_2 + X_1^2 + X_2^2 > 4 $$

#3
##a
```{r}
x1 = c(3,2,4,1,2,4,4)
x2 = c(4,2,4,4,1,3,1)
y=c(1,1,1,1,0,0,0)
plot(x1,x2, col= as.factor(y), xlim=c(-5, 5), ylim=c(-5, 5))
```
```{r}
library(e1071)
svmfit = svm(y~., data= data.frame(x1, x2))
plot(x1,x2, col= as.factor(y), xlim=c(0, 5), ylim=c(0, 5))
abline(-0.5,1)
```
##c
-0.5X + X2 >0 classify as red.

##d
```{r}
plot(x1,x2, col= as.factor(y), xlim=c(0, 5), ylim=c(0, 5))
abline(-0.5, 1)
abline(-1, 1, lty=2)
abline(0, 1, lty=2)
```
##e
```{r}
plot(x1,x2, col= as.factor(y), xlim=c(0, 5), ylim=c(0, 5))
abline(-0.5, 1)
abline(-1, 1, lty=2)
abline(0, 1, lty=2)

points(2,2, pch=22, cex = 3)
points(2,1, pch=22, cex = 3)
points(4,4, pch=22, cex = 3)
points(4,3, pch=22, cex = 3)

```











