---
title: "chp7 ex11"
author: "kwon"
date: "2018년 8월 23일"
output: html_document
---

#11
##a
```{r}
set.seed(1)
X1 = rnorm(100)
X2 = rnorm(100)
eps = rnorm(100, sd=0.1)
Y = -2 + 3 * X1 + 4 * X2 + eps
```

##bc
```{r}
beta1 = 3
a = Y-beta1*X1
beta2 = lm(a~x2)$coef[2]
beta2

beta2= 4
a=y-beta2*x2
beta1 = lm(a~x1)$coef[2]
beta1
```

##e
```{r}
beta0 = rep(0,1000)
beta1 = rep(0,1000)
beta2 = rep(0,1000)
beta1[1]=10

for (i in 1:1000) {
  a = Y - beta1[i] * X1
  beta2[i] = lm(a~X2)$coef[2]
  a = Y - beta2[i] * X2
  lm.fit = lm(a~X1)
  if (i < 1000) {
    beta1[i+1] = lm.fit$coef[2]
  }
  beta0[i] = lm.fit$coef[1]
}
plot(1:1000, beta0, type="l", xlab="iteration", ylab="betas", ylim=c(-2.2, 1.6), col="green")
lines(1:1000, beta1, col="red")
lines(1:1000, beta2, col="blue")
legend('center', c("beta0","beta1","beta2"), lty=1, col=c("green","red","blue"))
```

```{r}
lm.fit = lm(Y~X1+X2)
plot(1:1000, beta0, type="l", xlab="iteration", ylab="betas", ylim=c(-2.2, 1.6), col="green")
lines(1:1000, beta1, col="red")
lines(1:1000, beta2, col="blue")
abline(h=lm.fit$coef[1], lty="dashed", lwd=3, col=rgb(0, 0, 0, alpha=0.4))
abline(h=lm.fit$coef[2], lty="dashed", lwd=3, col=rgb(0, 0, 0, alpha=0.4))
abline(h=lm.fit$coef[3], lty="dashed", lwd=3, col=rgb(0, 0, 0, alpha=0.4))
legend('center', c("beta0","beta1","beta2", "multiple regression"), lty=c(1, 1, 1, 2), col=c("green","red","blue", "black"))
```















